### ISSUE TITLE
[FEAT] 스타일 관련 QA 반영

### ISSUE THREAD

**Issue by Hanna922** [Central-MakeUs/All-Chive-Mobile#111]
## Description
할당된 스타일 관련 QA 반영 

## TODO
- [x] 모든 수정 화면에서 버튼 문구 '완료'로 변경
- [x] 마이페이지, 내 계정에서 하단 노란색 배경 제거
- [x] 계정 삭제 버튼 디자인 변경
- [x] 내 계정 페이지 프로필 패딩 수정
- [x] 아카이빙 카드의 컨텐츠 갯수 표시 부분 폰트, 패딩 변경
