### ISSUE TITLE
[FEAT] 제일중요 우선순위 QA 스타일 변경

### ISSUE THREAD

**Issue by EmilyPPP** [Central-MakeUs/All-Chive-Mobile#113]
## Description

할당된 제일중요 우선순위 QA 스타일 변경

## TODO

- [x] 홈, 커뮤니티 그라데이션 변경
- [x] 카테고리 sticky 시 배경 변경
- [x] 왼쪽 화살표 아이콘 변경
