### ISSUE TITLE
[FEAT] QA 중요 스타일링 추가

### ISSUE THREAD

**Issue by EmilyPPP** [Central-MakeUs/All-Chive-Mobile#122]
## Description

QA 중요 스타일링 추가

## TODO

- [x] 컨텐츠 메모, 태그 없을 경우 안보여지도록
- [x] 햄버거 버튼 아이콘 1.5배 키우기
- [x] 고정/삭제 팝업 스타일링
