### ISSUE TITLE
[FEAT] QA 보통 우선순위 기능 

### ISSUE THREAD

**Issue by EmilyPPP** [Central-MakeUs/All-Chive-Mobile#133]
## Description

QA 보통 우선순위 기능 

## TODO

- [x] 헤더 제목 위치 맞춤
- [x] 텍스트 인풋 박스 X 버튼 추가
- [x] 닉네임 수정 모달 헤더 위치 맞춤
- [x] 메모에 글자수 보여주기 추가
- [x] empty item 이미지 변경 
- [x] 체크박스 색상 변경
