### ISSUE TITLE
[FEAT] 회원가입 디자인 변경

### ISSUE THREAD

**Issue by EmilyPPP** [Central-MakeUs/All-Chive-Mobile#163]
## Description

회원가입 디자인을 변경합니다

## TODO

- [x] 체크박스 선택 후 Yellow fill로 변경
- [x] 에러 메세지 빨간 색으로 변경
- [x] RootStack 리팩토링
- [x] 화면 구성 반응형으로 변경
